name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup module and run unit tests
      run: |
        npm install
        npm run test:ci
      env:
        CI: true
        REACT_APP_PUBLIC_KEY: ${{ secrets.ik_public_key }}
        REACT_APP_PRIVATE_KEY: ${{ secrets.ik_private_key }}
        REACT_APP_URL_ENDPOINT: ${{ secrets.ik_url_endopint }}

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup module and build test-app
      run: |
        npm install
        npm run build
        cd tests/test-app
        echo REACT_APP_URL_ENDPOINT = ${{ secrets.ik_url_endopint }} > .env;
        npm install
        npm run build

    - name: Run E2E tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run serve:test-app
        wait-on: http://localhost:4000
      env:
        CI: true
        REACT_APP_PUBLIC_KEY: ${{ secrets.ik_public_key }}
        REACT_APP_PRIVATE_KEY: ${{ secrets.ik_private_key }}
        REACT_APP_URL_ENDPOINT: ${{ secrets.ik_url_endopint }}
